//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryMachine.MemberService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberData", Namespace="http://schemas.datacontract.org/2004/07/LotteryMachineService")]
    [System.SerializableAttribute()]
    public partial class MemberData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SexIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SexId {
            get {
                return this.SexIdField;
            }
            set {
                if ((this.SexIdField.Equals(value) != true)) {
                    this.SexIdField = value;
                    this.RaisePropertyChanged("SexId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MemberService.IMemberService")]
    public interface IMemberService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberService/AddMember", ReplyAction="http://tempuri.org/IMemberService/AddMemberResponse")]
        void AddMember(LotteryMachine.MemberService.MemberData member);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberService/AddMember", ReplyAction="http://tempuri.org/IMemberService/AddMemberResponse")]
        System.Threading.Tasks.Task AddMemberAsync(LotteryMachine.MemberService.MemberData member);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberService/GetAllMembers", ReplyAction="http://tempuri.org/IMemberService/GetAllMembersResponse")]
        LotteryMachine.MemberService.MemberData[] GetAllMembers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberService/GetAllMembers", ReplyAction="http://tempuri.org/IMemberService/GetAllMembersResponse")]
        System.Threading.Tasks.Task<LotteryMachine.MemberService.MemberData[]> GetAllMembersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberService/GetMemberById", ReplyAction="http://tempuri.org/IMemberService/GetMemberByIdResponse")]
        LotteryMachine.MemberService.MemberData GetMemberById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberService/GetMemberById", ReplyAction="http://tempuri.org/IMemberService/GetMemberByIdResponse")]
        System.Threading.Tasks.Task<LotteryMachine.MemberService.MemberData> GetMemberByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberService/EditMember", ReplyAction="http://tempuri.org/IMemberService/EditMemberResponse")]
        void EditMember(LotteryMachine.MemberService.MemberData member);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberService/EditMember", ReplyAction="http://tempuri.org/IMemberService/EditMemberResponse")]
        System.Threading.Tasks.Task EditMemberAsync(LotteryMachine.MemberService.MemberData member);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberService/DeleteMember", ReplyAction="http://tempuri.org/IMemberService/DeleteMemberResponse")]
        void DeleteMember(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberService/DeleteMember", ReplyAction="http://tempuri.org/IMemberService/DeleteMemberResponse")]
        System.Threading.Tasks.Task DeleteMemberAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMemberServiceChannel : LotteryMachine.MemberService.IMemberService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MemberServiceClient : System.ServiceModel.ClientBase<LotteryMachine.MemberService.IMemberService>, LotteryMachine.MemberService.IMemberService {
        
        public MemberServiceClient() {
        }
        
        public MemberServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MemberServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddMember(LotteryMachine.MemberService.MemberData member) {
            base.Channel.AddMember(member);
        }
        
        public System.Threading.Tasks.Task AddMemberAsync(LotteryMachine.MemberService.MemberData member) {
            return base.Channel.AddMemberAsync(member);
        }
        
        public LotteryMachine.MemberService.MemberData[] GetAllMembers() {
            return base.Channel.GetAllMembers();
        }
        
        public System.Threading.Tasks.Task<LotteryMachine.MemberService.MemberData[]> GetAllMembersAsync() {
            return base.Channel.GetAllMembersAsync();
        }
        
        public LotteryMachine.MemberService.MemberData GetMemberById(int id) {
            return base.Channel.GetMemberById(id);
        }
        
        public System.Threading.Tasks.Task<LotteryMachine.MemberService.MemberData> GetMemberByIdAsync(int id) {
            return base.Channel.GetMemberByIdAsync(id);
        }
        
        public void EditMember(LotteryMachine.MemberService.MemberData member) {
            base.Channel.EditMember(member);
        }
        
        public System.Threading.Tasks.Task EditMemberAsync(LotteryMachine.MemberService.MemberData member) {
            return base.Channel.EditMemberAsync(member);
        }
        
        public void DeleteMember(int id) {
            base.Channel.DeleteMember(id);
        }
        
        public System.Threading.Tasks.Task DeleteMemberAsync(int id) {
            return base.Channel.DeleteMemberAsync(id);
        }
    }
}
